remote_theme: pmarsceill/just-the-docs



# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/


title: Lehrbuch ÖGD

# Aux links for the upper right navigation
aux_links:
  "Lehrbuch auf GitHub":
    - "https://github.com/akademie-oeffentliches-gesundheitswesen/lehrbuch-oeffentliche-gesundheit"
  "PDF":
    - "https://github.com/akademie-oeffentliches-gesundheitswesen/lehrbuch-oeffentliche-gesundheit"
    
logo: "akademie.jpeg"
